### ISSUE TITLE
Just bought 5 pcs Solum 2.9

### ISSUE THREAD

**Issue by denstol** [wiggertdehaan/open_epaper_link_homey#24]
I saw your homey app and went to search where I can buy those things and bought 5 pieces right away, but now I'm unsure if I need anything else. Does it communicate directly with the internal zigbee interface of the homey device? I hope so 😂
And how do I need to 'connect' those Devices when they are installed first? Can I alter see them as ESPhome devices.
Sorry, lots of newbie questions, but OK. Looking forward to play with those things.

**Comment by wiggertdehaan** [comment]
Hey there, you do need an Accesspoint to get it to work with Homey. You can install it yourself, but the easy way is just to buy one: https://www.tindie.com/products/electronics-by-nic/openepaperlink-mini-ap-v3-zigbee-wifi-gateway/
