### ISSUE TITLE
Doc request - Wiki update

### ISSUE THREAD

**Issue by MagTer** [wiggertdehaan/open_epaper_link_homey#26]
Hi Wiggert,

I am very interested in what OpenEPaperLink has to offer but it would be good to get some more information in the wiki for how to use it. 

I found the openepaperlink.de website that talks about needing a wifi/802.15.4 gateway but I have not yet understood if Homey can provide this via the internal Zigbee controller.

Some simple guide for how to get going and possibly, where to get the right tags :)

It looks very promising so will for sure follow your work and openEPaperLink in the future.

**Comment by wiggertdehaan** [comment]
Good point! I will try to put some time in it ;-)

As for your question; 
tldr; You will need an extra AccessPoint. 

Zigbee is an implementation on the IEEE 802.15.4 standard. The AP does not use zigbee but does use the IEEE 802.15.4. I have not found a way (not sure if there is any) to directly use the IEEE 802.15.4 standard in Homey. That would allow to work with the tags directly.
