### ISSUE TITLE
Doesn't seem to connect to my acess point

### ISSUE THREAD

**Issue by Memlosch** [wiggertdehaan/open_epaper_link_homey#27]
Hi,

This app really have the potential to be great I think! :)

I'm having some installations problems though:

I have installed the app in homey and set the ip adress correctly.
Nothing shows up when I try to use the app in a flow.
It does show up when I try to add a new device, but it doesn't find any new devices.

Acess point info:
env: ESP32_S3_16_8_YELLOW_AP
build date: 2024-01-29 18:1

5 Solum 2,9" displays connected to the acess point and working.

Have I done anything wrong?

**Comment by wiggertdehaan** [comment]
Hi there, can you send a logfile with me? I'll have a look.

**Comment by Memlosch** [comment]
Done
Code 058e01ba-d3db-4c7b-b8d0-3a2c85abc256

**Comment by b00lt** [comment]
Any updates to this? I have basically the same issue...

**Comment by wiggertdehaan** [comment]
@Memlosch see my post in #28, the logfile does not give me all the information to get to the problem directly

**Comment by Memlosch** [comment]
Commented in https://github.com/wiggertdehaan/open_epaper_link_homey/issues/28
Should I close this issue?
