### ISSUE TITLE
Build support for HwType 2

### ISSUE THREAD

**Issue by Illerip** [wiggertdehaan/open_epaper_link_homey#30]
Version 1.3.0 solved it with HwType 17. 
The Solum M2 4.2” that Electronics by Nic sells seems to be yet another version. This has HwType 2.

I did send you an email about this.

BR
L-I

**Comment by wiggertdehaan** [comment]
Hey there, 

HwType 2 should be supported. Do you only have 2 or also other types of tags?

**Comment by Illerip** [comment]
The 4.2” tags I got is type 2 and the 2.9” tags are type 17. The picture supplied is from one of the 4.2.
![IMG_1946](https://github.com/wiggertdehaan/open_epaper_link_homey/assets/54694242/a7515a48-50ad-4436-8a07-5fdb028cb333)

**Comment by Illerip** [comment]
Strange. My AP had a newer firmware than the one available yesterday. But when I checked some minutes ago there was a new AP firmware named 2.5-beta. I installed that and now the 4.2 tags works as well in Homey.😃
