### ISSUE TITLE
7.4" Display

### ISSUE THREAD

**Issue by wizz666** [wiggertdehaan/open_epaper_link_homey#38]
Hi. 
Not an issue but would be nice to have the bigger 7.4" displays in the Homey app and not only the small displays.
Any thing you planing to add?

**Comment by wiggertdehaan** [comment]
Can you check what hardwar ID it has? Then adding it should not be too hard!

**Comment by b00lt** [comment]
<img width="141" alt="image" src="https://github.com/wiggertdehaan/open_epaper_link_homey/assets/38104320/531ed654-2626-4ea7-aa32-b9b98d6afdc2">

**Comment by wiggertdehaan** [comment]
Yes, thanks!

**Comment by wizz666** [comment]
Will be nice to have the big displays in the app :)

**Comment by wiggertdehaan** [comment]
Test version available, let me know!
https://homey.app/nl-nl/app/nl.wiggert.OpenEPaperLink/OpenEPaperLink/test/

**Comment by b00lt** [comment]
Found the device and its now added. having other issues that it is not updating. note sure since its showing error in the AP GUI...

But so far your update works, thanks!

**Comment by wizz666** [comment]
Will try this tonight after work and see how it works for me :)

**Comment by wizz666** [comment]
Well i got it to work so i think it will be good :) 
Thanks for adding it to the App.
